### ISSUE TITLE
A message from your supervisor

### ISSUE THREAD

**Issue by adam-waldenberg** [ptibom/Kelde#1]
Hi. I hope easter-time has treated everyone well. I'm just dropping a note here in preparation for next week.

Don't forget the domain model seminar on Monday. The seminar will be supervised by myself and Joachim in two separate locations; please refer to the course page to find the location and time slot specific to your group.

You will give a quick explanation of your application/game and present your domain model. If you have a UI mockup, include this in your presentation as well. Come well-prepared; you only have 5 minutes for your presentation, with 5 minutes of questions from the supervisor and other students (10 minutes in total as a maximum).

On Thursday, we will talk more about design and cover code coverage, PMD, FindBugs and STAN. If you are not using Maven, make sure your build rules can generate code coverage reports, PMD reports and FindBugs reports. You should also make sure that it's possible to build your project from a terminal. We will also go through your RAD. Also, don't forget; you should be able to show me an initial (first) running use case.

Good Luck and see  you on Thursday, at the latest :).

**Comment by ptibom** [comment]
Thank you for the reminder. We have reworked our use-cases and UML.

We do have a working demo of our game with a player, map and collision detection. We also have working animations for monsters in a separate branch but it is not yet implemented in the master branch because we need to get our MVC straight first (this week).
